In [1]:
import numpy as np
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
import numpy as np
a = np.zeros((3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np
a = np.random.randint(1, 11, size=(5, 5))
print(a)

[[ 6  9  6  9  5]
 [ 2 10  3  2  6]
 [ 9  7  1  6  2]
 [ 6  8  8  9  6]
 [ 8  4 10  5  3]]


In [13]:
import numpy as np
a = np.random.rand(4, 4)
print(a)

[[0.24851408 0.68114286 0.36236291 0.81572852]
 [0.86213126 0.53080242 0.19435586 0.53920863]
 [0.20248875 0.26849451 0.02147422 0.40114655]
 [0.79035062 0.64359354 0.03602578 0.9047276 ]]


In [15]:
import numpy as np
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
addition = a + b
subtraction = a - b
multiplication = a * b
print(addition)
print(subtraction)
print(multiplication)

[11  9 19  9 10]
[-7 -5 -1  7  0]
[18 14 90  8 25]


In [17]:
import numpy as np
a = np.random.rand(7)
b = np.random.rand(7)
print(np.dot(a, b))

1.8574096572239527


In [19]:
import numpy as np
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print(np.dot(a, b))

[[102  98  98]
 [ 72  96  96]]


In [22]:
import numpy as np
a = np.random.randint(1, 11, size=(3, 3))
print(np.linalg.inv(a))

[[-0.3         0.2         0.25      ]
 [ 0.07272727 -0.10909091  0.04545455]
 [ 0.41818182 -0.12727273 -0.36363636]]


In [25]:
import numpy as np
a = np.random.rand(4, 4)
print(a.T)

[[0.91518973 0.06506362 0.97908084 0.68513635]
 [0.37095109 0.46481914 0.01820696 0.05426704]
 [0.04367183 0.23164328 0.57224771 0.94859652]
 [0.13222307 0.17471017 0.7177819  0.75492357]]


In [27]:
import numpy as np
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
print(np.dot(a, b))

[160  36 123]


In [28]:
import numpy as np
a = np.random.rand(2, 3)
b = np.random.rand(3)
print(np.dot(a, b))

[0.18665914 0.17273827]


In [29]:
import numpy as np
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a*b)

[[27  9]
 [ 4 60]]


In [30]:
import numpy as np
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(np.dot(a, b))

[[42 73]
 [67 73]]


In [31]:
import numpy as np
a = np.random.randint(1, 101, size=(5, 5))
print(np.sum(a))

1127


In [32]:
import numpy as np
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(a-b)

[[ 0  3  0 -3]
 [-8  5 -4 -3]
 [-5 -9  5  1]
 [ 3  0  7 -1]]


In [35]:
import numpy as np
a = np.random.rand(3, 3)
row_sums = np.sum(a, axis=1)
column_vector = row_sums.reshape(-1, 1)
print(column_vector)

[[1.74167172]
 [1.12064948]
 [2.21207806]]


In [37]:
import numpy as np
a = np.random.randint(1, 11, size=(3, 4))
print(np.square(a))

[[ 25   9  36  64]
 [ 81   9  64  49]
 [100  49  36 100]]


In [38]:
import numpy as np
a = np.random.randint(1, 51, size=4)
print(np.sqrt(a))

[3.74165739 5.         6.78232998 3.87298335]
